environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g grunt-cli

test_script:
  - node --version && npm --version
  - grunt build

build: off

matrix:
  fast_finish: true
